#!/usr/bin/env bash

export S3_BUCKET_NAME=""
export AWS_REGION=""

aws s3 mb s3://"$(echo $S3_BUCKET_NAME)" \
    --region "$(echo $AWS_REGION)" \
    --endpoint-url https://s3."$(echo $AWS_REGION)".amazonaws.com
